version: '3.8'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      PRISMA_BINARY_TARGETS: '["native","linux-musl-openssl-3.0.x"]'
      DATABASE_URL: postgresql://postgres:postgres@db:5432/fazenda
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: fazenda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

